baseurl = "https://fahimscirex.github.io"
DefaultContentLanguage = "en"
title = "Fahim Montasir"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true
pygmentOptions = "linenos=inline"
#disqusShortname = "fahimscirex"
#googleAnalytics = "262790099"
summaryLength = "80"
#enableGitInfo = true

[Params]
  homeTitle = "fahimscirex" # Set a different text for the header on the home page
  subtitle = "can't see what's coming"
  mainSections = ["post","posts"]
  logo = "img/avatar.webp" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
#  commit = true
#  rss = true
#  comments = true
#  readingTime = true
#  wordCount = true
  useHLJS = true
  socialShare = true
  toc = true
#  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Fahim Montasir Misbah"
  website = "https://fahimscirex.github.io"
  email = "fahimscirex@tutanota.com"
#  facebook = "username"
  github = "fahimscirex"
#  gitlab = "username"
#  bitbucket = "username"
  twitter = "fahimscirex"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
  spotify = "fahimscirex"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
  telegram = "themanfrombakerstreet"
#  500px = "username"
#  codepen = "username"
  mastodon = "fosstodon.org/web/accounts/313800"
#  kaggle = "username"
#  weibo = "username"
#  slack = "username"

#[[menu.main]]
#    name = "Blog"
#    url = ""
#    weight = 1

[[menu.main]]
    identifier = "topics"
    name = "Blog"
    weight = 2

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    parent = "topics"
    name = "Book Reviews"
    url = "/categories/book-review"
    weight = 1

[[menu.main]]
    parent = "topics"
    name = "Linux"
    url = "/categories/linux"
    weight = 2

[[menu.main]]
    parent = "topics"
    name = "Journal"
    url = "/categories/journal"
    weight = 3

[[menu.main]]
    name = "Categories"
    url = "categories"
    weight = 3
[[menu.main]]
    name = "Contact"
    url = "/page/contact"
    weight = 3
